---
dashboard:
  enabled: true
  statistics:
    recentErrors: 100
debug:
  enabled: false
externalTrafficPolicy: Local
rbac:
  enabled: true
ssl:
  enabled: true
  enforced: true
acme:
  enabled: true
  staging: false
  logging: true
  challengeType: http-01
  email: jencub@gmail.com
  persistence:
    enabled: false
resources:
  limits:
    cpu: 2
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi
podDisruptionBudget:
  maxUnavailable: 1
replicas: 3
metrics:
  serviceMonitor:
    enabled: false
  prometheus:
    enabled: false
kvprovider:
  storeAcme: true
  consul:
    endpoint: "jc-consul-server.consul.svc.cluster.local:8500"
    watch: true
# debug:
#   enabled: true
